services:
  - type: worker
    name: brendbot2
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TIMEZONE
        value: Asia/Almaty
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
